---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: nitric
release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - make generate
    - make build-dashboard
builds:
  - env:
      - CGO_ENABLED=0
    id: nitric
    binary: nitric
    ldflags:
      - -s -w -X github.com/nitrictech/cli/pkg/version.Version={{.Version}} -X github.com/nitrictech/cli/pkg/version.Commit={{.Commit}} -X github.com/nitrictech/cli/pkg/version.BuildTime={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64
      archives:
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
scoop:
  bucket:
    owner: nitrictech
    name: scoop-bucket
  homepage: "https://nitric.io"
  description: "Nitric CLI"
  license: Apache 2.0

brews:
  - name: nitric
    tap:
      owner: nitrictech
      name: homebrew-tap
    commit_author:
      name: nitric-bot
      email: maintainers@nitric.io
    folder: Formula
    homepage: "https://nitric.io/"
    description: "Nitric CLI"
    license: "Apache 2.0"
    dependencies:
      - name: git
      - name: pulumi # needed for certain provider deployments
        type: optional
