// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nitrictech/newcli/pkg/containerengine (interfaces: ContainerEngine)

// Package mock_containerengine is a generated GoMock package.
package mock_containerengine

import (
	io "io"
	reflect "reflect"

	types "github.com/docker/docker/api/types"
	container "github.com/docker/docker/api/types/container"
	network "github.com/docker/docker/api/types/network"
	gomock "github.com/golang/mock/gomock"
	containerengine "github.com/nitrictech/newcli/pkg/containerengine"
)

// MockContainerEngine is a mock of ContainerEngine interface.
type MockContainerEngine struct {
	ctrl     *gomock.Controller
	recorder *MockContainerEngineMockRecorder
}

// MockContainerEngineMockRecorder is the mock recorder for MockContainerEngine.
type MockContainerEngineMockRecorder struct {
	mock *MockContainerEngine
}

// NewMockContainerEngine creates a new mock instance.
func NewMockContainerEngine(ctrl *gomock.Controller) *MockContainerEngine {
	mock := &MockContainerEngine{ctrl: ctrl}
	mock.recorder = &MockContainerEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerEngine) EXPECT() *MockContainerEngineMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockContainerEngine) Build(arg0, arg1, arg2 string, arg3 map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockContainerEngineMockRecorder) Build(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockContainerEngine)(nil).Build), arg0, arg1, arg2, arg3)
}

// ContainerCreate mocks base method.
func (m *MockContainerEngine) ContainerCreate(arg0 *container.Config, arg1 *container.HostConfig, arg2 *network.NetworkingConfig, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCreate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCreate indicates an expected call of ContainerCreate.
func (mr *MockContainerEngineMockRecorder) ContainerCreate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCreate", reflect.TypeOf((*MockContainerEngine)(nil).ContainerCreate), arg0, arg1, arg2, arg3)
}

// ContainerExec mocks base method.
func (m *MockContainerEngine) ContainerExec(arg0 string, arg1 []string, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerExec", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContainerExec indicates an expected call of ContainerExec.
func (mr *MockContainerEngineMockRecorder) ContainerExec(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerExec", reflect.TypeOf((*MockContainerEngine)(nil).ContainerExec), arg0, arg1, arg2)
}

// ContainersListByLabel mocks base method.
func (m *MockContainerEngine) ContainersListByLabel(arg0 map[string]string) ([]types.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainersListByLabel", arg0)
	ret0, _ := ret[0].([]types.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainersListByLabel indicates an expected call of ContainersListByLabel.
func (mr *MockContainerEngineMockRecorder) ContainersListByLabel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainersListByLabel", reflect.TypeOf((*MockContainerEngine)(nil).ContainersListByLabel), arg0)
}

// CopyFromArchive mocks base method.
func (m *MockContainerEngine) CopyFromArchive(arg0, arg1 string, arg2 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFromArchive", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFromArchive indicates an expected call of CopyFromArchive.
func (mr *MockContainerEngineMockRecorder) CopyFromArchive(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFromArchive", reflect.TypeOf((*MockContainerEngine)(nil).CopyFromArchive), arg0, arg1, arg2)
}

// ListImages mocks base method.
func (m *MockContainerEngine) ListImages(arg0, arg1 string) ([]containerengine.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", arg0, arg1)
	ret0, _ := ret[0].([]containerengine.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockContainerEngineMockRecorder) ListImages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockContainerEngine)(nil).ListImages), arg0, arg1)
}

// NetworkCreate mocks base method.
func (m *MockContainerEngine) NetworkCreate(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkCreate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// NetworkCreate indicates an expected call of NetworkCreate.
func (mr *MockContainerEngineMockRecorder) NetworkCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkCreate", reflect.TypeOf((*MockContainerEngine)(nil).NetworkCreate), arg0)
}

// Pull mocks base method.
func (m *MockContainerEngine) Pull(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockContainerEngineMockRecorder) Pull(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockContainerEngine)(nil).Pull), arg0)
}

// RemoveByLabel mocks base method.
func (m *MockContainerEngine) RemoveByLabel(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByLabel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveByLabel indicates an expected call of RemoveByLabel.
func (mr *MockContainerEngineMockRecorder) RemoveByLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByLabel", reflect.TypeOf((*MockContainerEngine)(nil).RemoveByLabel), arg0, arg1)
}

// Start mocks base method.
func (m *MockContainerEngine) Start(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockContainerEngineMockRecorder) Start(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockContainerEngine)(nil).Start), arg0)
}
