# Where should we write the GIF?
Output new_project_demo.gif

Set Framerate 16

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1900
Set Height 1400

# Type a command in the terminal.
Type "../bin/nitric new"

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s

Type "example-project&"

Sleep 4s

Backspace

Sleep 2s

Enter

Sleep 4s

Down

Sleep 1s

Down

Sleep 1s

Up

Sleep 1s

Enter

Sleep 15s