name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          github-token: ${{ secrets.NITRIC_BOT_TOKEN }}
          project-url: 'https://github.com/orgs/nitrictech/projects/3'
          
