---
name: Publish

on:
  push:
    # run only against tags
    tags:
      - '*'

env:
  FATHOM_SITE: ${{ vars.FATHOM_SITE }}

jobs:
  publish:
    name: GoReleaser
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 1.18
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.NITRIC_BOT_TOKEN }}
